name: Docker image cicd

on:
 
  workflow_dispatch:  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag=my-image-name:v1
        docker run -d -p 8080:8080 -p 9990:9990 my-image-name:v1 
        pwd
        ls
        curl http://localhost:8080
      
    - name: Upload image
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        name: first_image
        image: "myimage-name:v1"
